### ISSUE TITLE
404 errors at live demo page

### ISSUE THREAD

**Issue by vitro-mod** [dgreenheck/tree-js#6]
![image](https://github.com/dgreenheck/tree-js/assets/108282310/eb61e3f1-2420-44c5-bf28-ffd509816ef0)

**Comment by dgreenheck** [comment]
Thanks, I am aware of this issue. I'm currently updating the repository so it can be consumed as an npm package, so things are a bit broken. I'll let you know when I'm done.

**Comment by dgreenheck** [comment]
This has been resolved.
